// ─────────────────────────────────────────────
//  PitchBridge Demo Data
//  Used when NEXT_PUBLIC_DEMO_MODE=true
//  (i.e. GitHub Pages / offline demo)
// ─────────────────────────────────────────────

export const DEMO_USER = {
    id: 'demo-user-001',
    email: 'demo@pitchbridge.com',
    name: 'Demo User',
    role: 'FOUNDER',
    onboarded: true,
    avatar: null,
};

export const DEMO_STARTUPS = [
    {
        id: 'demo-startup-001',
        name: 'NeuralPay',
        sector: 'FinTech',
        stage: 'seed',
        problem: 'Over 1.4 billion adults remain unbanked globally, with traditional payment rails being too slow, expensive, and inaccessible for emerging markets.',
        solution: 'NeuralPay provides AI-powered payment infrastructure with real-time fraud detection, multi-currency support, and embedded finance APIs.',
        traction: '12,000 monthly active users, $2M GMV processed',
        marketSize: '$120B TAM in African fintech by 2025',
        fundingAsk: 2000000,
        llmScore: 82,
        llmTags: ['FinTech', 'AI', 'Emerging Markets'],
        llmSummary: 'NeuralPay addresses a massive pain point in emerging market payments with an AI-first approach.',
        screeningStatus: 'APPROVED',
        founder: { user: { name: 'Sarah Chen' } },
    },
    {
        id: 'demo-startup-002',
        name: 'EcoCharge',
        sector: 'CleanTech',
        stage: 'pre-seed',
        problem: 'Electric vehicle charging is too slow and inaccessible for commercial fleets.',
        solution: 'High-speed modular battery swapping stations powered by solar energy.',
        traction: '3 pilot partnerships signed with logistics companies',
        marketSize: '$50B EV charging market by 2030',
        fundingAsk: 1500000,
        llmScore: 88,
        llmTags: ['CleanTech', 'EV', 'Solar', 'Logistics'],
        llmSummary: 'EcoCharge presents a scalable solution to a critical bottleneck in EV adoption.',
        screeningStatus: 'APPROVED',
        founder: { user: { name: 'Raj Mehta' } },
    },
    {
        id: 'demo-startup-003',
        name: 'MindBridge AI',
        sector: 'HealthTech',
        stage: 'series-a',
        problem: 'Mental health care is inaccessible and expensive for 80% of those who need it.',
        solution: 'An AI therapist that provides 24/7 personalized mental health support at a fraction of the cost.',
        traction: '50,000+ sessions completed, 4.8/5 avg rating',
        marketSize: '$500B global mental health market',
        fundingAsk: 5000000,
        llmScore: 91,
        llmTags: ['HealthTech', 'AI', 'Mental Health', 'B2C'],
        llmSummary: 'MindBridge AI combines LLM breakthroughs with clinical research to democratize mental healthcare.',
        screeningStatus: 'APPROVED',
        founder: { user: { name: 'Aisha Patel' } },
    },
    {
        id: 'demo-startup-004',
        name: 'LearnLoop',
        sector: 'EdTech',
        stage: 'seed',
        problem: 'Students forget 80% of what they learn within a week due to passive learning methods.',
        solution: 'Adaptive micro-learning platform that reinforces concepts through spaced repetition and AI-generated quizzes.',
        traction: '10,000 students onboarded, 3 school partnerships',
        marketSize: '$7.3B edtech market growing at 15% CAGR',
        fundingAsk: 800000,
        llmScore: 75,
        llmTags: ['EdTech', 'AI', 'B2B', 'SaaS'],
        llmSummary: 'LearnLoop leverages proven cognitive science methods with modern AI to improve learning outcomes.',
        screeningStatus: 'APPROVED',
        founder: { user: { name: 'Marcus Johnson' } },
    },
];

export const DEMO_JOBS = [
    {
        id: 'demo-job-001',
        title: 'Senior Full-Stack Engineer',
        description: 'Join our growing team to build the next generation of payment infrastructure. You will work on our core API, web dashboard, and integrations with regional payment providers.',
        skills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript'],
        type: 'FULL_TIME',
        salaryMin: 80000,
        salaryMax: 120000,
        equity: '0.5-1%',
        remote: true,
        active: true,
        founder: { user: { name: 'Sarah Chen' }, startupName: 'NeuralPay' },
        _count: { applications: 12 },
    },
    {
        id: 'demo-job-002',
        title: 'Machine Learning Engineer',
        description: 'We are looking for an ML engineer to develop our AI-powered battery optimization algorithms and predictive maintenance models for our charging infrastructure.',
        skills: ['Python', 'TensorFlow', 'PyTorch', 'MLOps'],
        type: 'FULL_TIME',
        salaryMin: 90000,
        salaryMax: 140000,
        equity: '0.25-0.75%',
        remote: false,
        active: true,
        founder: { user: { name: 'Raj Mehta' }, startupName: 'EcoCharge' },
        _count: { applications: 8 },
    },
    {
        id: 'demo-job-003',
        title: 'Product Designer (UI/UX)',
        description: 'Shape the experience for thousands of students. Design intuitive, delightful learning flows that keep students engaged and coming back.',
        skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
        type: 'FULL_TIME',
        salaryMin: 70000,
        salaryMax: 100000,
        equity: '0.1-0.5%',
        remote: true,
        active: true,
        founder: { user: { name: 'Marcus Johnson' }, startupName: 'LearnLoop' },
        _count: { applications: 25 },
    },
    {
        id: 'demo-job-004',
        title: 'Clinical AI Research Intern',
        description: 'Work alongside our clinical team and AI researchers to validate our mental health models and improve the quality of our AI therapy sessions.',
        skills: ['Python', 'NLP', 'Research', 'Psychology'],
        type: 'INTERNSHIP',
        salaryMin: 25000,
        salaryMax: 40000,
        equity: null,
        remote: true,
        active: true,
        founder: { user: { name: 'Aisha Patel' }, startupName: 'MindBridge AI' },
        _count: { applications: 43 },
    },
    {
        id: 'demo-job-005',
        title: 'DevOps / Infrastructure Engineer',
        description: 'Own our cloud infrastructure on AWS and ensure 99.99% uptime for our payment processing systems. Build the foundation for global scale.',
        skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD'],
        type: 'FULL_TIME',
        salaryMin: 85000,
        salaryMax: 130000,
        equity: '0.5-1%',
        remote: true,
        active: true,
        founder: { user: { name: 'Sarah Chen' }, startupName: 'NeuralPay' },
        _count: { applications: 6 },
    },
    {
        id: 'demo-job-006',
        title: 'Growth Marketing Lead',
        description: 'Drive user acquisition and retention for our platform. Own the full funnel from awareness to activation and build a growth engine from scratch.',
        skills: ['Digital Marketing', 'SEO', 'Analytics', 'A/B Testing'],
        type: 'FULL_TIME',
        salaryMin: 65000,
        salaryMax: 95000,
        equity: '0.25-0.5%',
        remote: true,
        active: true,
        founder: { user: { name: 'Marcus Johnson' }, startupName: 'LearnLoop' },
        _count: { applications: 19 },
    },
];

export const DEMO_FOUNDER_STATS = {
    jobs: [
        { ...DEMO_JOBS[0], active: true },
        { ...DEMO_JOBS[4], active: true },
    ],
    startup: DEMO_STARTUPS[0],
};

export const IS_DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === 'true';
